version: '3.7'
services:
  grpc-server:
    image: golang:1.13-stretch
    container_name: grpc-server
    tty: true
    volumes:
      - .:/root/
    working_dir: /root/

  grpc-client:
    image: golang:1.13-stretch
    container_name: grpc-client
    tty: true
    volumes:
      - .:/root/
    working_dir: /root/
